/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "s21_main_test.check" instead.
 */

#include <check.h>

#include <stdlib.h>
#include <string.h>

#include "s21_string.h"

START_TEST(strlen_test)
{
  const char str1[] = "";
  const char str2[] = "Hello";
  const char str3[] = "A";
  const char str4[] = "This is a test.";
  const char str5[] = "Another test with spaces";
  const char str6[] = "1234567890";
  const char str7[] = "Line\nNew line";
  const char str8[] = "\0Hidden";
  char str9[1024] = "Long string with a lot of characters...";
  const char str10[] = "Ends with space ";
  ck_assert_uint_eq(s21_strlen(str1), strlen(str1));
  ck_assert_uint_eq(s21_strlen(str2), strlen(str2));
  ck_assert_uint_eq(s21_strlen(str3), strlen(str3));
  ck_assert_uint_eq(s21_strlen(str4), strlen(str4));
  ck_assert_uint_eq(s21_strlen(str5), strlen(str5));
  ck_assert_uint_eq(s21_strlen(str6), strlen(str6));
  ck_assert_uint_eq(s21_strlen(str7), strlen(str7));
  ck_assert_uint_eq(s21_strlen(str8), strlen(str8));
  ck_assert_uint_eq(s21_strlen(str9), strlen(str9));
  ck_assert_uint_eq(s21_strlen(str10), strlen(str10));
  ck_assert_msg(0, "This test intentionally fails");

}
END_TEST

START_TEST(strlen_error_test)
{
  const char str11[] = "Hello";
  ck_abort_msg("This test intentionally fails");

}
END_TEST
START_TEST(memcmp_compare_start)
{
// Тест на сравнение начала строк
  size_t n1 = 3;
  char b1[1024] = "Hello,";
  char b11[1024] = "Hello,";
  char str_1_2[1024] = "Hello, World!";
  ck_assert_int_eq(memcmp(b1, str_1_2, n1), s21_memcmp(b11, str_1_2, n1));

}
END_TEST

START_TEST(memcmp_minimal_difference)
{
// Тест на сравнение строк с одним различающимся символом
  size_t n2 = 4;
  char b2[1024] = "1234";
  char str_2_2[1024] = "1235";
  ck_assert_int_lt(s21_memcmp(b2, str_2_2, n2), 0);

}
END_TEST

START_TEST(memcmp_identical_parts)
{
// Тест на сравнение одинаковых участков в строках
  size_t n3 = 4;
  char b3[1024] = "SB SB SB $! ";
  char str_3_3[1024] = "SB SB SB $! ";
  ck_assert_int_eq(memcmp(b3, b3 + 7, n3), s21_memcmp(str_3_3, str_3_3 + 7, n3));

}
END_TEST

START_TEST(memcmp_case_sensitivity)
{
// Тест на сравнение строк с учётом регистра
  size_t n4 = 6;
  char b4[1024] = "abcdef";
  char str_4_4[1024] = "abcDef";
  ck_assert_int_gt(s21_memcmp(b4, str_4_4, n4), 0);

}
END_TEST

START_TEST(memcmp_zero_chars)
{
// Тест на сравнение строк с нулевыми символами
  size_t n5 = 8;
  char b5[1024] = "a\0b\0c\0";
  char b55[1024] = "a\0b\0c\0";
  ck_assert_int_eq(s21_memcmp(b5, b55, n5), 0);

}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("s21_strlen_suite");
    TCase *tc1_1 = tcase_create("case_s21_strlen");
    Suite *s2 = suite_create("s21_memcmp_suite");
    TCase *tc2_1 = tcase_create("case_s21_memcmp");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, strlen_test);
    tcase_add_test(tc1_1, strlen_error_test);
    suite_add_tcase(s2, tc2_1);
    tcase_add_test(tc2_1, memcmp_compare_start);
    tcase_add_test(tc2_1, memcmp_minimal_difference);
    tcase_add_test(tc2_1, memcmp_identical_parts);
    tcase_add_test(tc2_1, memcmp_case_sensitivity);
    tcase_add_test(tc2_1, memcmp_zero_chars);

    srunner_add_suite(sr, s2);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    /* User-specified post-run code */
if (nf != 0) {
      printf("Hey, something's wrong! %d whole tests failed!\n", nf);
    }
    return 0;
}
